- name: Ensure django, Gunicorn and psycopg2 are installed
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - Django==1.11.6
    - djangorestframework==3.7.1
    - gunicorn==19.7.1
    - psycopg2==2.7.3.1
    - pytz==2017.2


- name: Create Systemd service file for Gunicorn
  template:
    src: 'gunicorn.service.j2'
    dest: '/etc/systemd/system/gunicorn.service'
    owner: root
    group: root
    mode: 'u=rw,g=r,o=r'
