---
- hosts: all
  connection: ssh
  user: vagrant
  become: true
  gather_facts: yes
  roles:
    - { role: 'local' }
    - { role: 'db',
        import-db: true
      }
    - { role: 'proxy' }
    - { role: 'gunicorn'}
    - { role: 'app' }
    - { role: 'ruby',
        ruby_install_gems: ['serverspec', 'rake']
      }
  post_tasks:
    - name: Start the Gunicorn service
      service: name=gunicorn state=started enabled=yes
